name: iOS Tests

on:
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      # Optional: Cache CocoaPods/SwiftPM here

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run unit tests
        run: |
          set -o pipefail && xcodebuild -project RoomRoster.xcodeproj \
            -scheme RoomRoster \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            OTHER_SWIFT_FLAGS="-Xfrontend -enable-experimental-feature -Xfrontend AccessLevelOnImport" \
            test | xcpretty
