name: iOS Unit Tests

on:
  pull_request:
    branches: [main, staging]

jobs:
  test:
    # macos-15 image ships with Xcode 16.x (Swift 6) pre-installed.
    runs-on: macos-15
    timeout-minutes: 30

    steps:
    # ────────────────────────────── 1. Checkout ──────────────────────────────
    - uses: actions/checkout@v4

    # ─────────────────────── 2. Run helper script ────────────────────────────
    - name: Run unit tests
      env:
        NSUnbufferedIO: "YES"          # live log streaming
      run: Scripts/ci-test.sh
    # ────────────── 5. Optional: capture DerivedData if the build fails ───────
    - name: Upload DerivedData (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: DerivedData
        path: ~/Library/Developer/Xcode/DerivedData
