name: iOS Tests

on:
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      - name: Create dummy Secrets.plist for CI
        run: |
          cat > RoomRoster/RoomRoster/RoomRoster/Secrets.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>API_KEY</key>
              <string>ci-fake-key</string>
              <key>SHEET_ID</key>
              <string>ci-fake-sheet-id</string>
          </dict>
          </plist>
          EOF

      - name: Create dummy GoogleService-Info.plist for CI
        run: |
          cat > RoomRoster/RoomRoster/RoomRoster/GoogleService-Info.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>BUNDLE_ID</key>
              <string>com.example.ci</string>
          </dict>
          </plist>
          EOF

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run unit tests
        run: |
          set -o pipefail && xcodebuild -project RoomRoster.xcodeproj \
            -scheme RoomRoster \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            OTHER_SWIFT_FLAGS="-Xfrontend -enable-experimental-feature -Xfrontend AccessLevelOnImport" \
            test | xcpretty
